---
#$y$j9T$ayrsnO7dO5eyVqo6QdveJ1$vsQlbMCWV2PGhYpLEWwEBJQqui8rEdpW0/GC3iJ6DeA
- hosts: all
  tasks:
    - name: Addtheuser
      ansible.builtin.user:
        name: k8sadm
        comment: regular user
#        uid: 1010
        group: adm
#        password: $y$j9T$DAWBd4qD2yh8YOsJ5gIEM0$E6Nn0k3JL01dLLjg2ETsM4qY9FzSYawpWHc4yN29Gs5
        password: "{{ '12345678' | password_hash('sha512') }}"
        shell: /usr/bin/bash
        state: present
        createhome: yes
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      become: true
    - name: Addtheuser
      ansible.builtin.user:
        name: k8sadm
        comment: kubernetes adm
        uid: 1010
        group: adm
        password: $y$j9T$DAWBd4qD2yh8YOsJ5gIEM0$E6Nn0k3JL01dLLjg2ETsM4qY9FzSYawpWHc4yN29Gs5
        shell: /usr/bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      become: true
    - name: allow sudo for wheel group
      ansible.builtin.copy:
        src: files/users.sudo
        dest: /etc/sudoers.d/users
        owner: root
        group: adm
        mode: '440'
      become: true
  roles:
    - role: roles/sysuser


...
